name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-format:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: "latest"

      - name: Set up Python
        run: uv python install 3.12

      - name: Run Ruff Lint Check
        run: uvx ruff check .

      - name: Run Ruff Format Check
        run: uvx ruff format --check .

  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: "latest"

      - name: Set up Python
        run: uv python install 3.12

      - name: Install project dependencies
        run: uv sync --extra dev

      - name: Run Pytest
        run: |
          uv run pytest -v || if [ $? -eq 5 ]; then echo "No tests collected, skipping."; else exit 1; fi
